version: '3.5'

services:
    portfoliov2-uwsgi:
        image: 057133510824.dkr.ecr.eu-west-3.amazonaws.com/portfoliov2:latest
        command: chmod +x ./deploy/prod/uwsgi && ./deploy/prod/uwsgi
        restart: always
        volumes:
            - type: bind
              source: /var/run/portfoliov2/
              target: /var/run/portfoliov2/
            - type: bind
              source: /var/dev_data/portfoliov2/log/
              target: /var/log/portfoliov2/
            - type: bind
              source: /var/dev_data/portfoliov2/
              target: /var/dev_data/portfoliov2/
            - type: volume
              source: datastatic
              target: /opt/portfoliov2/static_files
        deploy:
          resources:
            limits:
              memory: 200M

volumes:
    datastatic:
        name: portfoliov2_static