# Generated by Django 4.2.6 on 2023-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(upload_to='portfolio/static/img/'),
        ),
    ]
