# Generated by Django 4.2.6 on 2023-10-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/static/img/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
