# Generated by Django 4.2.6 on 2023-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_image_alter_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
